import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="preload"
          href="/fonts/bit9x9.ttf"
          as="font"
          type="font/ttf"
          crossOrigin=""
        />
      </head>
      <body>
        {children}
      </body>
    </html>
  );
}
